# General simulation settings
# variables:
#   &user_timesteps 18400

general:
  USER_TIMESTEPS: 18900               # Number of user timesteps
  IDENTIFIER_LENGTH: 12               # Number of characters in identifier

user_threshold:
  TOTAL_NUMBER_OF_USERS: 256          # Create only same set of users for different run
  ENABLE_USER_THRESHOLD: false        # Enable user threshold

# Movement Parameters
movement_parameters:
  POLYGON_COORDS:                     # Polygon coordinates
    - [3499.77, 1500.07]
    - [5798.43, 3799.93]
    - [6452.11, 3150.56]
    - [5401.44, 2099.71]
    - [5751.91, 1749.63]
    - [4500.10, 498.92]
  # MAX_STEP_SIZE: 2                    # Step size
  # PROBABILITY_PAUSE: 0.3              # Probability of pause
  # PAUSE_DURATION_MIN: 1               # Minimum pause duration
  # PAUSE_DURATION_MAX: 5               # Maximum pause duration

tracking_and_reconstruction_until:
  TRACKING_UNTIL:
    - 18256
    - 18500
    - 19400

# Randomization Intervals
randomization_intervals:
  # Bluetooth IDs refresh range uniform (in seconds)
  BLUETOOTH_MIN_REFRESH: 600
  BLUETOOTH_MAX_REFRESH: 2700

  # WiFi ID refresh range uniform (in seconds)
  WIFI_MIN_REFRESH: 10
  WIFI_MAX_REFRESH: 15

  # LTE refresh range uniform (in seconds)
  LTE_MIN_REFRESH: 100
  LTE_MAX_REFRESH: 300

#Transmission Intervals
transmission_intervals:
  # Bluetooth IDs transmit range uniform (in seconds)
  BLUETOOTH_MIN_TRANSMIT: 0.25
  BLUETOOTH_MAX_TRANSMIT: 5

  # WiFi ID transmit range uniform (in seconds)
  WIFI_MIN_TRANSMIT: 0.25
  WIFI_MAX_TRANSMIT: 15

  # LTE transmit range uniform (in seconds)
  LTE_MIN_TRANSMIT: 0.25
  LTE_MAX_TRANSMIT: 5

# Range for communication protocols
communication_range:
  BLUETOOTH_RANGE: 10                # Bluetooth range (in meters)
  WIFI_RANGE: 30                     # WiFi range (in meters)
  LTE_RANGE: 100                     # LTE range (in meters)

# Localization errors
localization_errors:
  BLUETOOTH_LOCALIZATION_ERROR: 1    # Bluetooth localization error (in meters)
  WIFI_LOCALIZATION_ERROR: 5         # WiFi localization error (in meters)
  LTE_LOCALIZATION_ERROR: 10         # LTE localization error (in meters)

# Mobility settings
mobility:
  MAX_MOBILITY_FACTOR: 1.66          # Mobility factor in m/s

# Sniffer settings
sniffer:
  ENABLE_BLUETOOTH: false            # Enable Bluetooth
  SNIFFER_PROCESSING_BATCH_SIZE: 100 # Sniffer processing batch size
